---
title: Cascadia Massage and Health Centre
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Cascadia Massage and Health Centre
description: 
baseurl: ''
url: http://cascadiahealth.ca/
sass:
  style: compressed
social: 
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
markdown: kramdown
highlighter: rouge
permalink: pretty
