---
title: Cascadia Massage and Health Centre
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: 
baseurl: ''
url: http://cascadiahealth.ca/
data-ad-slot: 
data-ad-client: 
google_ad_client: 
google_analytics: 
addthis_id: 
disqus_account: 
social: 
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
gems:
- jekyll-paginate
- jekyll-feed
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
