---
timezone: America/Los_Angeles

author: Cascadia Massage and Health Centre
title: Cascadia Massage and Health Centre
description:

baseurl: ''
url: http://cascadiahealth.ca/
sass:
  style: compressed
social: 
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
markdown: kramdown
highlighter: rouge
permalink: pretty