---
title: Cascadia Massage and Health Centre
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: 
baseurl: ''
url: http://cascadiahealth.ca/
social: 
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
plugins:
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
